name: Test build

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
      - ci/test

jobs:
  release:
    name: Test build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the release step uses its own credentials:
          # https://github.com/cycjimmy/semantic-release-action#private-packages
          persist-credentials: false
          fetch-depth: 0

      - name: Cache Gradle
        uses: burrunan/gradle-cache-action@v1

      - name: Build
        env:
          GPR_USER: ${{ secrets.GPR_USER }}
          GPR_TOKEN: ${{ secrets.GPR_TOKEN }}
        run: ./gradlew build clean -Pgpr.user=${{ env.GPR_USER }} -Pgpr.key=${{ env.GPR_TOKEN }}

      - name: Upload Cli
        uses: actions/upload-artifact@v4
        with:
          name: Morphe
          path: build/libs/*-all.jar